version: '3.5'
services:
  auto:
    image: amos0626/auto
    container_name: auto
    ports:
      - '7000:8080'
    volumes:
      - './logs:/root/logs'
    environment:
      - JSCH_HOST=xxx.xxx.xxx.xxx
      - JSCH_USERNAME=root
      - JSCH_PASSWORD=xxx
      - COMMAND=./update.sh
    cap_add:
      - SYS_PTRACE